### ISSUE TITLE
Trading along a route

### ISSUE THREAD

**Issue by psolyca** [awhipp/evetrade#146]
**Is your feature request related to a problem? Please describe.**
Could be related to #80 .
When choosing a start and an end station, it could be greate to see all possible trading along the path to avoid travelling with not filled hold bay.

**Describe the solution you'd like**
I do not know yet ^^
Complex table to present

**Comment by awhipp** [comment]
Agreed. This is one and the same. I closed it due to complexity and time required but it is still something that would be a net-benefit if implemented effectively. Was largely concerned with time requirements if it crosses multiple regions. Would also need to get the buy and sell orders for all the regions it is in.

**Comment by psolyca** [comment]
I have written an algorithm and I will try to implement it.
BTW I have to find a way to keep the data from a region if multiple stations are passing through.
I did not look at the code for order fetching.

**Comment by awhipp** [comment]
Ideally this can be accomplished if we are be able to cache if a region was already retrieved or not. If it has then we just continue rather than process it.
