### ISSUE TITLE
Possible Bug? Perhaps just a question from a newbie.

### ISSUE THREAD

**Issue by adam10414** [awhipp/evetrade#176]
https://github.com/awhipp/evetrade/blob/a52a4ecbe0c5f323ef8ca4a804fc8a07c70bdc7f/js/station-trade.js#L269-L286

[Example](https://evetrade.space/?trade=sst&start=Jita&sales_tax=&broker_fee=&min_margin=&max_margin=&min_volume=)

It's listing buy price from sell orders, and sell price to buy orders. While this is expected, all of the buy orders are smaller than the sell orders. (Which is kind of expected if people are smart.) 

What I don't understand is how does this tool predict a profit if we're selling the item at a loss?

**Comment by awhipp** [comment]
This function is getting the specific best price (sell and buy) for a specific itemId at a specific region/station.

When it comes to trading within a station, THIS IS NOT for instant earnings unlike hauling.

* Station trading is the process of setting a buy order and selling once someone sells to you. Here's more information: https://wiki.bravecollective.com/public/dojo/wiki/station_trading_complete_guide
* Hauling is instant profit (semi-instant since you need to travel). In that case you are buying instant orders, and selling to instant orders.
